AWSTemplateFormatVersion: '2010-09-09'
Description: IAM roles for Odoo ECS tasks

Resources:
  OdooTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: odoo-task-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: odoo-execution-extras
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  OdooTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: odoo-task-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: odoo-task-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - elasticfilesystem:ClientMount
                  - elasticfilesystem:ClientWrite
                  - elasticfilesystem:ClientRootAccess
                Resource: '*'
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: '*'

Outputs:
  OdooTaskExecutionRoleArn:
    Value: !GetAtt OdooTaskExecutionRole.Arn
    Export:
      Name: OdooTaskExecutionRoleArn

  OdooTaskRoleArn:
    Value: !GetAtt OdooTaskRole.Arn
    Export:
      Name: OdooTaskRoleArn
