AWSTemplateFormatVersion: '2010-09-09'
Description: Secrets Manager secret for Odoo admin password

Resources:
  OdooAdminSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: odoo/admin-password
      Description: Odoo master admin password
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: password
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

Outputs:
  OdooAdminSecretArn:
    Value: !Ref OdooAdminSecret
    Export:
      Name: OdooAdminSecretArn
