AWSTemplateFormatVersion: '2010-09-09'
Description: ECR repository for Odoo CRM v19

Resources:

  OdooEcrRepositoryV19:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: odoo-crm-v19
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 10 tagged images",
                "selection": {
                  "tagStatus": "tagged",
                  "tagPrefixList": ["v"],
                  "countType": "imageCountMoreThan",
                  "countNumber": 10
                },
                "action": { "type": "expire" }
              },
              {
                "rulePriority": 2,
                "description": "Remove untagged images older than 7 days",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 7
                },
                "action": { "type": "expire" }
              }
            ]
          }
      Tags:
        - Key: Name
          Value: odoo-crm-v19

Outputs:
  OdooEcrRepositoryUriV19:
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/odoo-crm-v19"
    Export:
      Name: OdooEcrRepositoryUriV19
